CREATE DATABASE IF NOT EXISTS ecommerce;
USE ecommerce;

CREATE TABLE if NOT EXISTS Utenti(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Email VARCHAR(255) NOT NULL,
	password_utente VARCHAR(16) NOT NULL,
	tipo INT
);

CREATE TABLE if NOT EXISTS opzioni(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Nome VARCHAR(25),
	costo FLOAT
);

CREATE TABLE if NOT EXISTS Prodotti(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Nome VARCHAR(50),
	quantita INT,
	id_opzioni INT FOREIGN KEY,
	FOREIGN KEY (id_opzioni) REFERENCES opzioni (id) 
);